version: '3.4'

services:
  vora:
    image: vora
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3003:3003
      - 9229:9229
    command: ["NODE_ENV=production","node", "--inspect=0.0.0.0:9229", "index.js"]
